# Generated by Django 5.1.6 on 2025-07-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtCollectionCallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_id', models.CharField(blank=True, max_length=200)),
                ('call_id', models.CharField(blank=True, default='', max_length=1000)),
                ('call_time', models.DateTimeField(null=True)),
                ('recording', models.FileField(null=True, upload_to='CallRecordings')),
                ('call_duration', models.IntegerField(null=True)),
                ('conclusion', models.CharField(blank=True, default='Nothing', max_length=512)),
                ('call_summary_notes', models.CharField(blank=True, default='', max_length=1024)),
                ('conversation_json', models.JSONField(default=dict)),
                ('mode_of_payment', models.CharField(max_length=50, null=True)),
                ('promise_date', models.DateField(null=True)),
                ('promise_amount', models.FloatField(blank=True, null=True)),
                ('disconnect_type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'debtcollectioncallhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebtCollectionCallQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('partner_company_name', models.CharField(blank=True, max_length=200)),
                ('customer_id', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ocp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_overdue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('call_connected', models.BooleanField(default=False, null=True)),
                ('call_tried', models.IntegerField(default=0, null=True)),
                ('calling_status', models.BooleanField(default=False)),
                ('call_date', models.DateField(auto_now_add=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('reattempt_count', models.IntegerField(default=0)),
                ('last_call_tried', models.DateTimeField(blank=True, null=True)),
                ('offer', models.CharField(blank=True, max_length=1000, null=True)),
                ('cd_valid_till', models.DateField(blank=True, null=True)),
                ('cd_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cd_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'debtcollectioncallqueue',
                'managed': False,
            },
        ),
    ]
